/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import javax.swing.WindowConstants;
import keystroke.User;

/**
 *
 * @author Sithara wanigasooriy
 */
public class FirstPage extends javax.swing.JFrame {

    /**
     * Creates new form FirstPage
     */
    private User user1;
    public FirstPage() {
        initComponents();
        setMinimumSize(new Dimension (700,500));
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeLabel = new javax.swing.JLabel();
        HomeLogin = new javax.swing.JButton();
        HomeSignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        getContentPane().setLayout(null);

        HomeLabel.setBackground(new java.awt.Color(153, 153, 153));
        HomeLabel.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        HomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeLabel.setText("KEY STROKE DYNAMIC AUTHENTICATION");
        getContentPane().add(HomeLabel);
        HomeLabel.setBounds(40, 70, 610, 170);

        HomeLogin.setText("Login");
        HomeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeLoginActionPerformed(evt);
            }
        });
        getContentPane().add(HomeLogin);
        HomeLogin.setBounds(470, 360, 100, 32);

        HomeSignUp.setText("Signup");
        HomeSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(HomeSignUp);
        HomeSignUp.setBounds(110, 360, 100, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sithara wanigasooriy\\Documents\\GitHub\\BioMetric-Authentication-Keystroke-\\KeyStrokeAuthentication\\ispy-keylogger-sold-on-dark-web-for-25-found-targeting-passwords-webcams-and-skype.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 690, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeLoginActionPerformed
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_HomeLoginActionPerformed

    private void HomeSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSignUpActionPerformed
        // TODO add your handling code here:
        new SignUpPage(user1).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JButton HomeLogin;
    private javax.swing.JButton HomeSignUp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
